version: '3.8'

services:
  web:
    build: .
    container_name: kelio-app
    ports:
      - "5000:5000"
    environment:
      - SCRAPER_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - APP_DEBUG=${APP_DEBUG:-false}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONPATH=/app
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-kelio-scraper-secret-key}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    working_dir: /app
    command: python src/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
