services:
  # Web service with integrated scraper functionality
  - type: web
    name: kelio-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /app
      - key: SCRAPER_ENV
        value: production
    plan: free
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1